// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/DariaGori/Product_Api/Controllers"
	"github.com/DariaGori/Product_Api/Repositories"
	"github.com/DariaGori/Product_Api/Services"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitProductController(db *gorm.DB) Controllers.ProductController {
	productRepository := Repositories.ProvideProductRepostiory(db)
	productService := Services.ProvideProductService(productRepository)
	productController := Controllers.ProvideProductController(productService)
	return productController
}

func InitProductCategoryController(db *gorm.DB) Controllers.ProductCategoryController {
	productCategoryRepository := Repositories.ProvideProductCategoryRepostiory(db)
	productCategoryService := Services.ProvideProductCategoryService(productCategoryRepository)
	productCategoryController := Controllers.ProvideProductCategoryController(productCategoryService)
	return productCategoryController
}
